apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  selector:
    app: todoapp
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels: 
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: davidpapworth2/todo_app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: 'mysql+pymysql://root:root@35.242.185.109/picks'
        - name: SECRET_KEY
          value: hgjkeebhgvbhjbvfhj
