version: "3.8"
services:
    todo_app:
        container_name: todo_app
        image: davidpapworth2/todo_app
        build: .
        environment:
          DATABASE_URI: 'mysql+pymysql://root:root@35.242.185.109/picks'
          SECRET_KEY: hgjkeebhgvbhjbvfhj
        ports:
        - published: 5000
          target: 80